### ISSUE TITLE
What should methods be called for converting instance state to an object

### ISSUE THREAD

**Issue by jbphet** [phetsims/together#106]
When converting an object to JSON for transmission over the API, there is a step where the object must be converted into an object that captures its state data and that lends itself to easy conversion to JSON.  We've been using the name toJSON and the converse fromJSON, but these aren't really accurate, since that not really returning a JSON string or taking JSON as the parameter.  We should rename these methods to something more accurate.  Some ideas are serialize/deserialize, toState/fromState,

**Comment by jbphet** [comment]
@pixelzoom and @jonathanolson should opine on this, since these methods will appear in potentially lots of places in common code.

**Comment by pixelzoom** [comment]
No strong opinion.

**Comment by samreid** [comment]
I am leaning toward the instance method `serialize` plus the static method `deserialize`.  Definition from MSDN via Google (emphasis added):

> Serialization is the process of converting an object into a stream of bytes in order to store the object or transmit it to memory, a database, or a file. *Its main purpose is to save the state of an object in order to be able to recreate it when needed.* The reverse process is called deserialization.

**Comment by samreid** [comment]
On the other hand, is a plain old javascript object really a "stream of bytes"?

**Comment by jonathanolson** [comment]
toJSON/fromJSON and serialize/deserialize both imply to me returning a string or accepting a string (or possibly typed array for serialization).

toState/fromState (or toStateObject/fromStateObject) slightly preferred, but I'll be fine with any option.

**Comment by jbphet** [comment]
@samreid and I looked at this blog post entitled "There's no such thing as a 'JSON Object'", and I thought it helped clarify the debate a little.

I like @jonathanolson's suggestions.  @samreid - do you like the sound of toStateObject/fromStateObject, or would this cause confusion with other together operations?

**Comment by samreid** [comment]
to/fromStateObject sounds good to me.  Let's go for it.

**Comment by samreid** [comment]
Saw this code in r.js:

```js
    toJSON: function() {
        return {
            names: this.names,
            uses_eval: this.uses_eval,
            uses_with: this.uses_with
        };
    }
```

**Comment by samreid** [comment]
Also saw this in poly2tri.js:

```js
  Point.prototype.toJSON = function() {
    return { x: this.x, y: this.y };
  };
```

**Comment by samreid** [comment]
Despite other developers using toJSON to return an object literal, I think we should proceed to rename things as to/fromObjectState to make it clear what is happening.

**Comment by samreid** [comment]
Fixed above, closing.
