### ISSUE TITLE
Simplify tandem usage in common code

### ISSUE THREAD

**Issue by samreid** [phetsims/together#109]
I'm seeing this pattern quite a lot in common code instrumented with tandem:

```js
tandem: options.tandem && options.tandem.createTandem( 'reportAProblemButton' )
```

Perhaps it could be replaced with utility code like so:
```js
tandem: Tandem.extend(options,'reportAProblemButton')
```

Here, we could factor out all of the logic regarding what to do with null options, etc and still remain compatible with the same api.  Even sweeter icing on the cake would be if Tandem was a global so we wouldn't have to import `var Tandem=require('TANDEM/Tandem')` in every file that wants to use this pattern.

It would be good to discuss this with @jbphet or @pixelzoom before proceeding.

**Comment by pixelzoom** [comment]
I don't mind `options.tandem && options.tandem.createTandem(...)`.  It's obvious what's going on.  And it's a pattern used elsewhere, e.g. `assert && assert(...)`.  The proposed utility looks less obvious to me.

**Comment by samreid** [comment]
OK, let's continue with `options.tandem && options.tandem.createTandem(...)`, thanks for your thoughts.  Closing.
