### ISSUE TITLE
use a more descriptive name than "API"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/together#11]
The API that's used to access sim components via `together` is being referred to as "API".  This has propagated into code (getAPI), GitHub issues, and now branch names (see https://github.com/phetsims/faradays-law/issues/61).  This is confusing; in addition to the API that each piece of JavaScript code naturally defines, we are also in the process of defining other APIs: accessibility, translation,...  And it creates unnecessary refactoring work.

Please choose a more descriptive name, and let's start using it ASAP.

**Comment by pixelzoom** [comment]
An API is typically a set of routines, protocols and tools.  The `together` repo defines the routines and command protocols. Another part of the protocol is the routes to components, and the function `getAPI` might be better named `getTogetherRoutes` since it's assembling the protocol (routes) used to access sim components.

**Comment by samreid** [comment]
How about a public instance variable on Sim called `togetherAPI` indicating that it is the API for interoperating with all features under the "together" umbrella?

**Comment by pixelzoom** [comment]
`togetherAPI` sounds like a fine name. And if Sim is going to be a singleton, then making it a public instance variable sounds OK.   As an alternative, would `window.phet.together.api` provide equivalent convenience, while not putting the responsibility with Sim?

**Comment by samreid** [comment]
> togetherAPI sounds like a fine name. And if Sim is going to be a singleton, then making it a public instance variable sounds OK.

Yes, sim is already a singleton which can be accessed as `phet.joist.sim`.

> As an alternative, would window.phet.together.api provide equivalent convenience, while not putting the responsibility with Sim?

I'd like the togetherAPI to live in the sim code--I'm sure there are many ways to do it, but passing it as an option to Sim.js and passing that through to together.js (as we do now) seems reasonable to me.  But let me know if you can think of a superior alternative.

**Comment by pixelzoom** [comment]
@samreid and I discussed putting all of the sim API files (*-api.js) in the together repo.  I guess they could then be added to the HTML file, as the together support is.  Eg:

```
  <!--Scripts for together.js enhanced features-->
  <script type="text/javascript" src="../sherpa/jsondiffpatch-0.1.31.js"></script>
  <script type="text/javascript" src="../together/js/together.js"></script>
  <script type="text/javascript" src="../together/js/SimIFrameAPI.js"></script>
  <script type="text/javascript" src="../together/js/arch.js"></script>
  <script type="text/javascript" src="../together/js/datamite.js"></script>
  <script type="text/javascript" src="../together/js/concentration-together-api.js"></script>
```

If they lived in together, then could probably drop "together" from the file name. Eg, `../together/js/concentration-api.js` instead of `../together/js/concentration-together-api.js`.

**Comment by pixelzoom** [comment]
Not sure what else needs to be done on this, or what other input is needed from me. Assigning to @samreid.

**Comment by samreid** [comment]
I moved the files above, and I think everything for this issue is complete.  Closing.
