### ISSUE TITLE
Internal API for PropertySet property component IDs

### ISSUE THREAD

**Issue by samreid** [phetsims/together#15]
We need a optional way to associated Properties with componentIDs.  For new Propery() this is easy, because we can pass it in as an option.

For PropertySets, we need another way.  I can envision two approaches, not sure what others will prefer.  I'll paste them here from an example in Faraday's Law.  Whatever pattern we choose will permeate our codebase, so please think about this carefully and let me know which is better, @jbphet @pixelzoom @aaronsamuel137 @jonathanolson 

```js
    // (A) Pass a componentIDMap as options to the PropertySet
    PropertySet.call( this, {
      position: new Vector2( x, y ),
      flipped: false, //is magnet flipped
      showFieldLines: false // show field lines for magnet
    }, {
      componentIDMap: {
        position: 'faradaysLawScreen.magnet.position'
      }
    } );
```

OR

```js
    // (B) Nested within each property value.  We could also format this to put value/componentID on the same line if you prefer.
    PropertySet.call( this, {
      position: {
        value: new Vector2( x, y ),
        componentID: 'faradaysLawScreen.magnet.position'
      },
      flipped: false, //is magnet flipped
      showFieldLines: false // show field lines for magnet
    } )
```

**Comment by samreid** [comment]
some tradeoffs:

Using {value/componentID} means no duplication of the key name, but special handling for values that have value/componentID structure

Putting the map in options is similar to how we are using componentIDs elsewhere (as an option), but then it gets somewhat disassociated from the property itself (and duplicates the name, which may not be hard to maintain).

**Comment by samreid** [comment]
> Putting the map in options is similar to how we are using componentIDs elsewhere (as an option), but then it gets somewhat disassociated from the property itself (and duplicates the name, which may not be hard to maintain).

On the other hand, we could add asserts to make sure so that all given componentIDs match existing key names...

**Comment by jonathanolson** [comment]
(B) worries me a little bit, if we depend on checking hasOwnProperty for value/componentID. Imagine if we add componentIDs to bending-light's DataPoint type (it has .value) or a .value property to something with componentID, then presumably it would be discarded and its value would be used?

E.g.:
```js
function Type( value, componentID ) { this.value = value; this.componentID = componentID; }
var currentItem = new Type( 42, 'exampleSim.meaningOfLife' );
PropertySet.call( this, {
  // since currentItem has both properties, would this trigger itemProperty = new Property( 42 )
  // instead of new Property( currentItem )?
  item: currentItem
} );
```

**Comment by samreid** [comment]
Yes, I have the same concern @jonathanolson.  Should we try (A) for now, or can you think of better options?

**Comment by jonathanolson** [comment]
Are the componentIDs basically routes? I was anticipating it would be connected to that system for determining what the ID should be.

**Comment by samreid** [comment]
It is a unique identifier within a simulation for accessing a simulation component for configuration, data stream, save/load, interoperability etc.  For instance lines 39+ indicate componentIDs for concentration: https://github.com/phetsims/concentration/blob/together/js/concentration-together-api.js

**Comment by pixelzoom** [comment]
(A) is OK with me. But componentID is the base minimum that needs to be in the map. I'd like to see an example where the property is fully described (type, values if it's an enumeration,...)

**Comment by samreid** [comment]
> I'd like to see an example where the property is fully described (type, values if it's an enumeration,...)

I've been keeping this in the public together API declaration file.  To use concentration as an example:
```js
'concentrationScreen.soluteForm': { type: property( 'string' ), values: [ 'liquid', 'solid' ] },
//...
'concentrationScreen.solution.concentration': { type: property( 'number' ), units: 'mol/L' }
```

**Comment by samreid** [comment]
@jonathanolson & @aaronsamuel137 said (A) seems good for now.  @jbphet wants to take a closer look.

**Comment by jbphet** [comment]
I just reviewed the instrumented version of Faraday's Law with @samreid, and I'm okay with A, eh.

**Comment by samreid** [comment]
I think this plan is working acceptably well, closing.
