### ISSUE TITLE
Make sure together && arch lines get stripped out from production builds

### ISSUE THREAD

**Issue by samreid** [phetsims/together#17]
@jb suggested verifying together && arch get stripped out.

**Comment by samreid** [comment]
I can't figure out where this is happening in chipper, @jonathanolson or @pixelzoom can you help?

**Comment by jonathanolson** [comment]
See globalDefs in the main Gruntfile (line 56). Those global variable replacements are made (for implicit global reads, not for writes) before minification, then minification will strip the lines. Try adding "arch: false" to there.

**Comment by samreid** [comment]
Now that #72 has moved from arch=>trigger, we are wondering if we should strip those triggers out too.  Profiling should tell us the answer here.

**Comment by samreid** [comment]
We should be on the lookout for performance issues caused by the new triggers.  But I have not seen anything in passing and feel like this can move down a priority level in milestones.

**Comment by samreid** [comment]
Since #72 moved from arch => trigger, I think this issue is resolved.  If a profiler indicates too much time in the trigger() methods then we can investigate an appropriate solution at the time.
