### ISSUE TITLE
Improve throttling & filtering

### ISSUE THREAD

**Issue by samreid** [phetsims/together#23]
Moved from https://github.com/phetsims/arch/issues/1

We implemented a naive throttling algorithm which only sends the message if it has been >delay since the previous message.  However, when dragging a slider, this could omit the essential final value.  Could be handled separately in endDrag(), but @jonathanolson suggested:

> store a timestamp of last one, and don't send a message for it if it has been < delay

That would work well, but would require adding a message processing loop to run at each frame (or on a timer).  So it's currently implemented naively as described above, but we may want to switch to this new delay algorithm (to get the 'final' values) in the future.

**Comment by samreid** [comment]
By the way, Ido has reviewed naive throttling and said it will work well for the initial HTML5 studies.

**Comment by samreid** [comment]
In #2, @pixelzoom said:

> :star2: The design of the 'trottle' feature is questionable. I understand the need for 'thinning' lots of data (e.g. from a slider). But this implementation doesn't guarantee that a message is sent to indicate the final value that is selected. So the data is misleading/wrong.

**Comment by samreid** [comment]
I'd like arch to plug in to the sim's animation frame loop, so it can basically setTimeout/setInterval for certain throttled events to ensure we don't drop the last event.

**Comment by samreid** [comment]
One complication for throttling is what to do for children that are marked as throttled, but parents are not marked as throttled.  Maybe we should only permit throttling on roots?

**Comment by samreid** [comment]
I removed throttling in Property.js because it was getting too complicated--should be handled elsewhere as part of this issue.

**Comment by samreid** [comment]
We spoke about this with ETS and Ido today and they had good recommendations for how to markup the data for postprocess throttling.  I'll create a separate issue in together.

**Comment by samreid** [comment]
Ido said it is important to flag significant events in a large stream of related events.  For instance:

* Change of direction when dragging a slider
* When the user pauses when dragging a slider

Add flags into the data, so it can be filtered in postprocessing easily
Maybe just do this for sliders (not things that can be moved in 2 dimensions because the above quantities are more ambiguous)
Having PhET do it will not only decrease burden on other teams but increase consistency

@kathy-phet said: Put these clearly useful flags into the data, and provide an algorithm for filtering out the excess.

**Comment by samreid** [comment]
Here is some throttling code that filters out the common offenders (user drag, or model changed):

```js
    // When receiving a stack of messages, format a string and output to console.
    archListeners.push( function( message ) {
      var json = JSON.stringify( message, null, '  ' );

      if ( message.event === 'dragged' ) {
        return;
      }
      else if ( message.event === 'changed' && message.eventType === 'model' ) {

        // Ignore top level change events, caused by the model.
        return;
      }

      // Leave the quotes in the keys since it will make the console.log output match the output given to researchers
      console.log( json );
    } );
```

**Comment by samreid** [comment]
Perhaps a flexible way to proceed with filtering would be to enable filtering options with query parameters?

**Comment by samreid** [comment]
At today's meeting @kathy-phet suggested a query parameter that simply filters out intermediate messages.  And perhaps on dragEnd, perhaps we could also include a summary max/min.

**Comment by samreid** [comment]
@kathy-phet doesn't think this needs to be implemented before May 22.  First focus on getting the entire data set.

**Comment by pixelzoom** [comment]
I disagree with doing filtering at the time of data collection (e.g., via query parameters or other "switches" specific to filtering).  All data possible should be collected during data collection; you can't go back and collect missing data after the fact. Filtering should be done in post-processing.  If someone thinks that it's necessary in data collection, it's probably due to a problem with their post-processing techniques or process.  And implementing filtering as part of data collection will result in a more complicated implementation.

**Comment by samreid** [comment]
So hence we should focus our efforts on batching/compression to make sure bandwidth is not an issues?

**Comment by samreid** [comment]
@pixelzoom clarified: the filtering can happen in the parent frame before the data is stored.  That sounds great to me.  We can still use coarse filters such as "emitStates".

**Comment by dstein42** [comment]
We (metacog) leaves it in the hands of the sim creators to decide what to capture or send. It won't gag our backend and we try to do a good job of batching and retries to deal with spotty school networks. I would agree with Ido and Chris Malley (@pixelzoom)  that it's better to generate everything and filter in the parent frame (or in metacog). I also agree with @kathy-phet that we (metacog) don't need this filtering before May 22.

**Comment by samreid** [comment]
So I think all that remains for this issue is to provide a simple filtering example.  I created #111 for this and will close this issue.
