### ISSUE TITLE
Should we rename componentID to togetherID?

### ISSUE THREAD

**Issue by samreid** [phetsims/together#29]
Would it make things more consistent/cohesive/etc if we renamed componentID to togetherID?  I don't feel strongly one way or the other, but just wanted to get opinions from @aaronsamuel137 @pixelzoom @jonathanolson @jbphet since we will be typing it a lot in simulation code.

**Comment by pixelzoom** [comment]
togetherID is certainly more specific. And it would be easier to search for "together" to find all together-related code. Currently have to search for "together" and "componentID".

**Comment by samreid** [comment]
I was leaning toward renaming this to `togetherID` until I realized this term will appear in the 3rd party client usage.  And for 3rd party users of this code, it may make more sense to use the term `componentID` -- `togetherID` sounds a bit too much like an internal implementation detail.

**Comment by samreid** [comment]
After discussion today, we decided to go with `togetherID`.

**Comment by samreid** [comment]
I'm seeing 392 occurrences at the moment.

**Comment by samreid** [comment]
Done above, seems good for now.  Will reopen if I spot any other occurrences.  Closing.
