### ISSUE TITLE
Change property and array to be uppercase

### ISSUE THREAD

**Issue by samreid** [phetsims/together#33]
I originally chose property and array types to be lowercase to avoid lint issues, but this is causing inconsistencies in our type system.  Would be better if everything was uppercase for consistency, and let's just work around jshint in this case.

**Comment by pixelzoom** [comment]
Discussed with @samreid and @jbphet on 3/31/15...

Use lowercase for primitive types (string, number, boolean) for consistency with JSdoc type expression conventions.

Use uppercase for non-primitive types (Property, Vector2,...)

**Comment by samreid** [comment]
I'm presuming array should stay as lowercase, since function is lowercase in JSDoc.

**Comment by samreid** [comment]
Work completed above, closing.
