### ISSUE TITLE
Instrument another chemistry sim

### ISSUE THREAD

**Issue by samreid** [phetsims/together#35]
Before June we would like to have 2 physics + 2 chemistry sims instrumented.  We currently have good progress on:

* concentration
* color-vision
* faradays-law
* energy-skate-park-basics

Of this list, only concentration is chemistry, so we will need to pick another chemistry one.  On 3/27/15 I asked @kathy-phet what she recommends.

**Comment by kathy-phet** [comment]
Build an Atom would be great if you are up for the challenge of instrumenting a game!

**Comment by samreid** [comment]
Thanks for the quick reply @kathy-phet -- I think it would be good to do a game soon so we can make sure it is handled well.

**Comment by jbphet** [comment]
This was discussed today with @kathy-phet, and she suggested that we instrument Molecules and Light as the 2nd chemistry sim, which should be relatively easy, and then work on Build an Atom.  We should work on the non-game screens of BAA first, then the game.  We can then either provide Metacog with no BAA, BAA with the non-game screens instrumented, or BAA with full instrumentation, depending on how far we get by the deadline.

**Comment by jbphet** [comment]
@kathy-phet said that Acid-Base Solutions (ABS) is another simulation that would be good for this.  She had a slight preference for it over Molecules and Light, since ABS is a bit more clearly a chem sim, but left it up to the development team to decide which of the two to do based on ease of implementation.

**Comment by samreid** [comment]
I moved "Instrument Molecules and Light" to #88 with Imminent milestone.  I'll move Build an Atom to a new issue with Desirable milestone.
