### ISSUE TITLE
Simpler syntax for PropertySet componentIDs

### ISSUE THREAD

**Issue by samreid** [phetsims/together#49]
@pixelzoom previously avoided using PropertySet in Concentration in part because it is more of a hassle to assign componentIDs to constituent properties.  I ran into this issue in Build an Atom:

```js
    PropertySet.call( this,
      {
        // Properties that control label visibility in the view.
        showElementName: true,
        showNeutralOrIon: true,
        showStableOrUnstable: false,

        // Property that controls electron depiction in the view.
        electronShellDepiction: 'orbits'
      }, {

        // TODO: Could use the next line and dynamically generate everything 
        //componentIDContext:componentIDContext,

        componentIDMap: {
          showElementName: componentIDContext.createComponentID( 'showElementName' ),
          showNeutralOrIon: componentIDContext.createComponentID( 'showNeutralOrIon' ),
          showStableOrUnstable: componentIDContext.createComponentID( 'showStableOrUnstable' ),
          electronShellDepiction: componentIDContext.createComponentID( 'electronShellDepiction' ),
        }
      } )
```

Note the comment: we could provide an option to pass in a componentIDContext and let PropertySet autogenerate all of the ComponentIDs.  However, this should only be done when *all* properties can & should be registered with together, *and* when all of their code names match the API names.

**Comment by pixelzoom** [comment]
> @pixelzoom previously avoided using PropertySet in Concentration in part because it is more of a hassle to assign componentIDs to constituent properties.

My avoidance is documented in https://github.com/phetsims/beers-law-lab/issues/91

**Comment by samreid** [comment]
Thanks: the relevant line is:

> And the syntax for specifying together componentID is quite a bit uglier for PropertySet.

Do you think the proposed alternative would work well?

```js
    PropertySet.call( this,
      {
        // Properties that control label visibility in the view.
        showElementName: true,
        showNeutralOrIon: true,
        showStableOrUnstable: false,

        // Property that controls electron depiction in the view.
        electronShellDepiction: 'orbits'
      }, {
        componentIDContext:componentIDContext
      } )
```

**Comment by pixelzoom** [comment]
I guess I'm not clear on what a componentIDContext is, since I haven't looked at code that uses it yet. This looks better cosmetically. But the condition ("all properties can & should be registered with together, and when all of their code names match the API names") seems pretty restrictive and liable to be impact coding decisions. Ie, need to do things a different way when 1 or more properties don't meet this condition, or need to make big code changes if you want to add a property that doesn't meet this condition.

Just brainstorming here... What about something like below.  Properties that registered with together are specified as object literals with 'value' and 'componentID' fields. Properties not registered with together are just values.  Potential problems: (1) Not a fan of overloading like this, (2) There could be a problem if the value was something that had a value field and its own componentID.)

```js
PropertySet.call( this, {
  name: { value: true, componentID: 'name' },
  age: { value: 20, componentID: 'age' },
  favoriteColor: 'blue'
} );
```

**Comment by samreid** [comment]
Here's an alternative that avoids the overloading problem and avoids the problem (2) you mentioned:

```js
    PropertySet.call( this, {
      favoriteColor: 'blue'
    }, {
      propertiesWithIDs: {
        name: { value: true, componentID: 'name' },
        age: { value: 20, componentID: 'age' }
      }
    } );
```

**Comment by samreid** [comment]
At the moment, I'm leaning toward abandoning componentIDMap and adopting (experimenting with?) the last mentioned approach.  And possibly calling it "properties"--instead of "propertiesWithIDs".  It should be "propertiesWithOptions" but since it already appears in the options object, perhaps that is extraneous.   Also, this pattern could lead to numerous cases with {} for primary argument, such as:

```js
    PropertySet.call( this, {}, {
      properties: {
        name: { value: true, componentID: 'name' },
        age: { value: 20, componentID: 'age' }
      }
    } );
```

Is that acceptable?

I only want to do this once, so I want to hear from @pixelzoom and @jbphet before proceeding.  @jonathanolson and @aaronsamuel137 can chime in if they wish.

**Comment by pixelzoom** [comment]
>  And possibly calling it "properties"--instead of "propertiesWithIDs". 

The first parameter also enumerates properties (without IDs) so I don't like calling the 2nd parameter "properties". Perhaps "togetherProperties", to indicate that these are the properties that will be registered with together? 

As for the approach itself... I don't like the fact that you need to move property definitions to a different PropertySet arg when you instrument a sim. But this seems to be is a "lesser of evils" situation, so I'm torn about which approach is "best".

> I only want to do this once,

Agreed. I'd like to hear from the other developers, to see if there are strong opinions or other ideas.

**Comment by pixelzoom** [comment]
Assigning to @jonathanolson for input. Would be great to hear from @jbphet and @aaronsamuel137 too.

**Comment by samreid** [comment]
We could use a heuristic that "Any object passed to PropertySet that has exactly two properties which are `value` and `togetherID`" will be registered with together."  This seems like it would have a very low false positive rate, and wouldn't require moving things to different arguments when instrumenting a sim (though it does involve pushing a new object {}).  I'm still not sure which of the several alternatives is best.

**Comment by aaronsamuel137** [comment]
I like the approach of passing two objects, with one change - it seems like we could dispense with the extra field for ```propertiesWithIDs``` in the second object, i.e.:

```js
    PropertySet.call( this, {
      favoriteColor: 'blue'
    }, {
      name: { value: true, componentID: 'name' },
      age: { value: 20, componentID: 'age' }
    } );
```

As long as we document this API, I don't see this as being too confusing, and it will keep the code a little more concise.

**Comment by samreid** [comment]
>  it seems like we could dispense with the extra field for propertiesWithIDs in the second object, i.e.:

I'd like to reserve an `options` space for PropertySet, and passing togetherID through options is the convention elsewhere.

Just wanted to note that I have used togetherIDMap and it doesn't seem that bad--seems like a close match for other togetherID usage.

**Comment by jonathanolson** [comment]
As far as our needs go, adding the 2nd parameter to PropertySet's constructor sounds like the most useful and unambiguous.

I'd just like to note my personal preference that I'm still a bit concerned about the level of coupling between axon and together. I don't know the details of how things work currently, but I'd love to see it structured so that together is just one of the clients that could receive events and have components registered with axon.

**Comment by samreid** [comment]
> I'd just like to note my personal preference that I'm still a bit concerned about the level of coupling between axon and together. I don't know the details of how things work currently, but I'd love to see it structured so that together is just one of the clients that could receive events and have components registered with axon.

We should meet about this soon, since our design here will impact several projects with imminent deadlines.  I agree it would be beneficial for togetherEvents to just be a normal listener for instances, but that would make it more difficult to track nested events.  Would be great to discuss it together.

**Comment by samreid** [comment]
By the way, let's promote the last 1.5 comments to a new issue.

**Comment by samreid** [comment]
Yet another issues that will be eliminated by #72, it seems.

**Comment by samreid** [comment]
I think #72 has eliminated this problem.  For instance, instead of:

```js
    PropertySet.call( this, {
      showSecondCoil: false, // number of coils - 1 or 2
      showMagnetArrows: true
    }, {
      togetherIDMap: {
        showSecondCoil: 'faradaysLawScreen.showSecondCoil'
      }
    } );
```

We will now do:

```js
    PropertySet.call( this, {
      showSecondCoil: false, // number of coils - 1 or 2
      showMagnetArrows: true
    } );
//...
    // Together support
    together && together.addComponent( this.showSecondCoilProperty, 'faradaysLawScreen.showSecondCoil' );
```
