### ISSUE TITLE
constructor.name fails for compiled versions

### ISSUE THREAD

**Issue by samreid** [phetsims/together#56]
constructor.name fails for compiled versions, name is mangled.  We cannot use this for export/import.  There are occurrences of this in together/ and well as a few of the instrumented sims.  Must be fixed before we publish any togetherJS sims using these features.

**Comment by pixelzoom** [comment]
I don't understand this description. Can you clarify?

**Comment by samreid** [comment]
@jonathanolson said that when the sim is compiled, uglify2 mangles the constructor.name.  I was trying to use constructor.name==='DerivedProperty' in together, to see if something needed to be restored when loading a sim.  But it was always reporting false, and I suspected that constructor.name wasn't working properly.  I saw a few constructor.name occurrences throughout our repo, so wanted to raise this issue since it is something that might work during development but not after minification.

**Comment by samreid** [comment]
@jbphet & I also discovered this will bite us when it comes to reporting component type in the togetherEvents output.  We verified that it works great in the requirejs version but returns type = '' for everything in the minified version.  We'll need a new strategy here, hopefully one that doesn't have us duplicating the name too many times :(

**Comment by samreid** [comment]
Fixed above, we will be using WrapperType.typeName now instead of Function.name since that is removed during compilation.
