### ISSUE TITLE
postMessage order is not guaranteed?

### ISSUE THREAD

**Issue by samreid** [phetsims/together#57]
@jbphet & I noticed sighted several instances that suggested iframe messages were appearing out of order.  A quick search on the web suggested that window.postMessage receipt order is not guaranteed to match the send order.  We suspect this is causing a "received delta without receiving initial state" sometimes in phet-metacog.html.

@jbphet & I discussed moving toward a "one iframe-client per iframe" approach, instead of a "client can send to any iframe" client to make message reordering easier, if we indeed prove this is necessary.

**Comment by samreid** [comment]
Well, we are checking the order now.  If we ever see out of order messages, we can reopen this issue and add buffering to resort the messages.

**Comment by pixelzoom** [comment]
@samreid I'm having trouble grok'ing the above comment. Probably a typo. "resort the messages"?

**Comment by samreid** [comment]
"sort them again"

**Comment by pixelzoom** [comment]
Ah, re-sort: http://www.merriam-webster.com/dictionary/re-sort

Thanks.
