### ISSUE TITLE
Add sample processing utilities

### ISSUE THREAD

**Issue by samreid** [phetsims/together#59]
It would be good to create sample postprocessing applications that demonstrate how to analyze the event stream data.

**Comment by pixelzoom** [comment]
It would be better for filtering to live in post processing, rather than in the data collection.

**Comment by samreid** [comment]
> It would be better for filtering to live in post processing, rather than in data collection.

Agreed, but even more flexible may to design it so that it can easily be plugged into either phase, with our recommendation that it should be used in postprocessing if possible.

**Comment by pixelzoom** [comment]
As I wrote in https://github.com/phetsims/together/issues/23#issuecomment-91279265:

> I strongly disagree with doing filtering at the time of data collection (e.g., via query parameters or other "switches" specific to filtering). All data possible should be collected during data collection (the "firehose" approach); you can't go back and collect missing data after the fact. Filtering should be done in post-processing. If someone thinks that it's necessary in data collection, it's probably due to a problem with their post-processing techniques or process. And implementing filtering as part of data collection will result in a more complicated implementation.

**Comment by samreid** [comment]
I suspect bandwidth concerns and project-specific requirements may require some pre-filtering, unless we can find a way around those problems.

**Comment by ariel-phet** [comment]
Just to register my opinion here - I have already told this opinion to @kathy-phet - but I am in total agreement with @pixelzoom. Personally, I think all (and I mean *ALL*) filtering/post-processing etc should be the responsibility of someone using the data and not fall in our wheelhouse. 

I fear a slippery slope here, where we provide some filters, then people see that as something we do, and they start asking us for special case filters. If we do provide any filters we need to pick a very small subset, draw a reasonably firm "line in the sand" and say that any other filter request undergoes *serious* discussion before we do anything more than our small subset (and even ideally ask the requester to fund such work).

**Comment by pixelzoom** [comment]
@ariel-phet wrote:
> Personally, I think all (and I mean ALL) filtering/post-processing etc should be the responsibility of someone using the data and not fall in our wheelhouse.

Assuming PhET wants to bear the cost (which will be significant), I think it's fine to provide filtering utilities and examples. But filtering should be applied to *collected data*, not applied at the time of data collection.

**Comment by dstein42** [comment]
Agreed - we use Spark clusters to process data in parallel. Projecting out a subset of events is not a big deal. The psychometricians and data scientists want all the data since **they** want to decide what's relevant or not. As long as you don't degrade the performance of a running sim to the point where a student or educator becomes annoyed, we don't mind getting lots of "extra" data.

**Comment by samreid** [comment]
Looks like this is covered by #83 and #45, closing.
