### ISSUE TITLE
.js files at top level?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/together#6]
Why are together.js and datamite.js at the top level of the repo, instead of in the js/ directory?

**Comment by samreid** [comment]
I was following the policy (that I made up arbitrarily) that the js/ directory is for code loaded through the requirejs module loader, and files intended for clients to be included as scripts (specifically as a script tag) would be elsewhere.  Thoughts?

**Comment by pixelzoom** [comment]
Every sim's config.js file is loaded via a script tag and lives under js/.  I'd prefer to move all .js files under js/.  Otherwise, move all config.js files to the top-level for consistency.

**Comment by samreid** [comment]
together is neither a sim nor does it have a config.js file.  It is not meant to be used independently.

**Comment by pixelzoom** [comment]
I've made my opinion known. Other developers?

**Comment by samreid** [comment]
We decided to put it in js/

**Comment by pixelzoom** [comment]
Another good reason to put all .js files under js/ is that `grunt lint` only checks files under js/.

**Comment by samreid** [comment]
Fixed above, closing.
