### ISSUE TITLE
Publish an enhanced version of concentration

### ISSUE THREAD

**Issue by samreid** [phetsims/together#60]
We will be able to link to it as an example.

**Comment by pixelzoom** [comment]
What is "an enhanced version of concentration"?

**Comment by samreid** [comment]
With the together feature set bundled into the application.  @pixelzoom do you have strong feelings about where/how it should be published?  I was thinking of deploying it on spot, and versioning it with a name like 1.1.0-together.1 using the same build/deploy tools we use for normal dev deployments.

**Comment by pixelzoom** [comment]
1.1.0-together.1 on spot sounds good.

Should we add a `--together` option to the build process that adds the necessary files to the built HMTL file?

**Comment by pixelzoom** [comment]
1.1.0-together.1 on spot sounds good.

How do you plan to build something with together enabled? Should we add a `--together` option to the build process that adds the necessary files to the built HMTL file?

**Comment by samreid** [comment]
In the long term, perhaps a grunt option would be nice.  For now, the together branch of each repo should contain the additional scripts in the html and package.json files (currently only true for concentration).  But this current approach makes merging branches a pain :(

**Comment by samreid** [comment]
Issues we'll need to address for publishing this sim or other togetherjs sims: the "terms & conditions" link in the about dialog should be removed and the custom license wording should appear in the HTML file.

**Comment by samreid** [comment]
Here is the code in AboutDialog.js that adds the "terms & conditions" link:

```js
    if ( Brand.links && Brand.links.length ) {
      children.push( new VStrut( 15 ) );
      for ( var i = 0; i < Brand.links.length; i++ ) {
        var link = Brand.links[ i ];
        children.push( createLinkNode( link.text, link.url ) );
      }
    }
```

We could either (a) have together sims use a different Brand repo, or a Brand branch or (b) add custom logic here to handle this special case.  I guess I'm leaning toward a brand branch.

**Comment by samreid** [comment]
Added a `together` branch for the brand repo above, it will have to be used when publishing together sims.

**Comment by samreid** [comment]
This text is still appearing in the human-readable HTML header, and should be removed since it conflicts with the together license:
http://phet.colorado.edu/en/about/licensing

**Comment by samreid** [comment]
Here is the code in chipper that is adding that line of code we shouldn't have:

```js
    // Create the license header for this html and all the 3rd party dependencies
    var htmlHeader = pkg.name + '\n' +
                     'Copyright 2002-2013, University of Colorado Boulder\n' +
                     'PhET Interactive Simulations\n' +
                     'Licensed under ' + pkg.license + '\n' +
                     'http://phet.colorado.edu/en/about/licensing\n' +
                     '\n' +
                     'Libraries:\n' + global.phet.licenseText;
```

Should we add a switch to grunt to disable that line?  @jonathanolson @jbphet @pixelzoom @aaronsamuel137?

**Comment by samreid** [comment]
For now, I manually stripped out the offending line and published a version here:
http://www.colorado.edu/physics/phet/dev/html/concentration/1.2.0-together.1/concentration_en.html

**Comment by jbphet** [comment]
We also need to change the license field value in package.json from "GPLv3" to the text from the license file in the together repo, see https://raw.githubusercontent.com/phetsims/together/master/LICENSE.

**Comment by jbphet** [comment]
The steps necessary as of this moment are documented here: https://github.com/phetsims/together/blob/master/doc/publishing-a-sim.md.

**Comment by jbphet** [comment]
Since the steps are now documented, this issue will be closed.

**Comment by pixelzoom** [comment]
Reopening. I'm confused by the first step of the instructions:

> Make sure you're on the together branch or are using a repo that only produces together-enhanced sims, such as beaker.

At yesterday's meeting, we said that "enhanced" versions would be published out of the same branch as "basic" versions.  Why do we need a "together" branch?

**Comment by jbphet** [comment]
Enhanced version of beaker (stripped down Concentration) can be seen here, included a test wrapper: http://www.colorado.edu/physics/phet/dev/html/beaker/1.0.0-together.1/

**Comment by jbphet** [comment]
The long term plan is to have them published from the same branch, the short term plan is to use branches.  This will allow the approach to solidify before touching too much master branch code.

**Comment by pixelzoom** [comment]
Still confused... The 'together' branch of concentration was merged into 'master'.  So how do the instructions relate to publishing concentration?  Are you planning to re-create a 'together' branch?

**Comment by pixelzoom** [comment]
Mea culpa.  There is a "together" branch of concentration. There is not a "together" branch of beers-law-lab, which is where 99% of the code for concentration lives.   So why does "together" code live in beers-law-lab "master", and what is different about the "together" branch of concentration?

**Comment by samreid** [comment]
I broke up the URL above in case we don't want those to be reached through web crawlers or too public.

**Comment by samreid** [comment]
The together branch just contains the additional preload script references, and the different version number.

**Comment by samreid** [comment]
@jbphet and I are working on a grunt task that will remove the need for the together branches.  The HTMLs can live in together/.
