### ISSUE TITLE
API type declarations should use inheritance and wrap sim instances

### ISSUE THREAD

**Issue by samreid** [phetsims/together#73]
I think things would get a lot simpler if we created adapter wrappers for each sim instance that is instrumented, which has the desired together API.  Rather than calling static methods and passing in the instance as the first argument, and creating a whole bunch of new conventions to support it all.

**Comment by samreid** [comment]
If we do this, then instead of Type.componentAdded(component) it would be new Type(component), with an appropriate dispose method.

**Comment by samreid** [comment]
I've been experimenting with this, and it is simplifying many things.  Commit is imminent.

**Comment by samreid** [comment]
I sent out this email regarding this and #72:

> Based in part on a discussion I had yesterday with John Blanco and Jon Olson, I'll be making significant changes to the together repository as well as how beers-law-lab, sun, scenery-phet, axon are instrumented for together interoperability.  Jon Olson described a way to generalize the implementation to keep together modularized and prevent together logic from leaking into our common libraries. It looks good but it is a large refactor and I have been on a dirty working copy for 24+ hours now.  I'll let you know when it is ready to commit, and it will need some attention for review.

> Best Regards,
> Sam

**Comment by samreid** [comment]
I committed this above, and it is making things much nicer.  Some loose ends to convert to this strategy in Common.js and individual sim files.

**Comment by samreid** [comment]
This has been working great and solved numerous problems.  Fine tuning will follow in subsequent issues/commits but the big picture is done, closing.

**Comment by pixelzoom** [comment]
@samreid Related to this, is there an issue that deals with verifying that clients access only permitted fields?

**Comment by samreid** [comment]
I just created https://github.com/phetsims/together/issues/82
