### ISSUE TITLE
Create a sun component registry

### ISSUE THREAD

**Issue by samreid** [phetsims/together#80]
Inspired by #72 #79 and #77, I'm considering adding a "sun component registry" that would work like this:

(1) There would be a file like this which keeps track of all allocated sun instances:

```js
//  Copyright 2002-2014, University of Colorado Boulder

/**
 * The Sun Registry keeps track of all Sun user interface components that have been allocated.
 * It can be used for application-wide cross-cutting features.  For instance, you would be able to retrieve
 * All of the text buttons and increase their font, or change the color of all buttons.
 * It is also used by together.js
 *
 * @author Sam Reid (PhET Interactive Simulations)
 */
define( function( require ) {
  'use strict';

  // modules
  var inherit = require( 'PHET_CORE/inherit' );

  var components = [];

  /**
   *
   * @constructor
   */
  function SunRegistry() {
  }

  // Make available globally so it is easy to use (no require statement) since it will be partout
  window.sun.registry = SunRegistry;

  return inherit( Object, SunRegistry, {}, {
    addComponent: function( component ) {
      components.push( component );
    },
    removeComponent: function( component ) {
      var index = components.indexOf( component );
      if ( index !== -1 ) {
        components.splice( index, 1 );
      }
    },
    addComponentAddedListener:function(componentAddedListener){...},
    addComponentRemovedListener:function(componentRemovedListener){...},
    removeComponentAddedListener:function(componentAddedListener){...},
    removeComponentRemovedListener:function(componentRemovedListener){...},
  } );
} );
```

Here is an alternative implementation that may work equally well:

```js
//  Copyright 2002-2014, University of Colorado Boulder

/**
 * The Sun Registry keeps track of all Sun user interface components that have been allocated.
 * It can be used for application-wide cross-cutting features.  For instance, you would be able to retrieve
 * All of the text buttons and increase their font, or change the color of all buttons.
 * It is also used by together.js
 *
 * @author Sam Reid (PhET Interactive Simulations)
 */
define( function( require ) {
  'use strict';

  // modules
  var inherit = require( 'PHET_CORE/inherit' );
  var ObservableArray = require( 'AXON/ObservableArray' );

  /**
   *
   * @constructor
   */
  function SunRegistry() {
    ObservableArray.call( this );
  }

  // Make available globally so it is easy to use (no require statement) since it will be partout
  window.sun.registry = SunRegistry;

  return inherit( ObservableArray, SunRegistry, {}, {} );
} );
```

(2) When each sun instance is allocated, at the end of its constructor, it calls:

```js
sun.registry.addComponent(this);
```

This will make it possible to do things like change application-wide settings such as fonts, colors, etc, which may be useful for accessibility.  

(3) We could additionally provide an optional "id context" argument to each sun component.  If provided, it would assign the ID to the sun component during the constructor (before the addComponent call).  For any sub-components, it would create sub-contexts for their own IDs, which will maintain encapsulation:  (a) the component does not need to register sub-components as instance variables and (b) the client does not need to pass in multiple "id" values for the sub-components.  The ID context would behave like the current implementation of TogetherContext, but would be renamed to IDContext or idContext and moved to phet-core or some other upstream library.

(4) When together runs, it can add an observer to the sun registry so that when components are added, it can verify (a) that each sun component has an ID and (b) register the components with the together subsystem.

I know everything above seems complex, but it seems like it will provide the following advantages:
* address our encapsulation woes, so that clients don't need to know anything about the substructure of a sun component (aside from the sim-api.js file which would need to provide types for all components in the sim)
* solve #77 (guaranteeing that sun components are registered with together, when together is enabled)
* provide non-together features such as ability to control application fonts or colors (say, for accessibility)
* be an approach that can be used in every library as well as sim code (with the minor difference that in sun, the id's would be optional but in scenery-phet, joist and sims the id's would be required arguments).
* keep together-specific features out of sun, thus keeping it general

The main disadvantages:
* This will add new arguments (optional or required) to every sim/sun/joist/scenery-phet component that will have to be processed.
* Couples the implementation more tightly to the id chain.  Before doing this work, we had a lot of flexibility in naming components & sub-components, which could protect us from implementation refactoring appearing in the public API.  Making the id's part of the component structure would couple this more tightly.

This disadvantage is non-trivial, but my thought is that if done in a uniform and standard way, this cost and intrusiveness of this feature can be minimized.

@pixelzoom @jonathanolson @jbphet can we discuss this at your convenience?

EDIT: Added a second disadvantage.

**Comment by samreid** [comment]
One more thought about how this issue pertains to (Improve the pattern for customizability #20, the issue regarding customizing partially constructed objects).  If we consider each element added through an inheritance hierarchy as a separate entity--registered separately with the sun registry--then it will additionally solve the "partially constructed object" issue.  For instance, if TextButton extends RectangularButton, then at the end of RectangularButton constructor, the RectangularButton would be registered, then at the end of the TextButton constructor, the TextNode appearing on the button would additionally be registered as a separate component.  In the together API file, they would appear with IDs like:

```js
returnParticleButton:{type:Button},
returnParticleButton.textLabel:{type:TextLabel}
```

**Comment by samreid** [comment]
Just thinking of what else we may wish to use a sun component registry for.  Perhaps it could help us guarantee that we properly dispose() of all created sun components that need to be disposed.

**Comment by pixelzoom** [comment]
Comments:

(1) This approach seems to assume that every component added to the sun registry will also be registered with together. I'm not convinced that that is always desirable.

(2) Presumably the context will be an option to the constructor, and it's default will be null. Should together throw an Error when it attempts to register a component with null ID? Or should together ignore components with no ID?

(3) Every type that calls `sun.registry.addComponent` in its constructor must also implement `dispose`, which will call `sun.registry.removeComponent`.

(4) `sun.registry.addComponent( this )` needs an additional argument to specify the id that will be registered with together, e.g.: `sun.registry.addComponent( this, togetherID )`.  Call it `registryID` if you think it will have more general use. But if the ID is not specific to together, then the registry will need to keep a map of components and IDs.  And the option passed to the constructor will also need to be a generalized context that is not specific to together.  (Unless we envision a use for a more general ID, we may not want to open that can of worms.) 

(5) Presumably this approach should be applicable to other repositories, and not specific to sun.

Conclusion:

I don't know if this is a good approach. This is all getting very complicated.

**Comment by pixelzoom** [comment]
Assigning to @jonathanolson, since he was next on @samreid's feedback request list.

**Comment by samreid** [comment]
Here's an alternative to the sun component registry: 

Add an optional parameter to sun components which is a function that gets called when components are created.

For instance, say HSlider has a track and knob.  Then at the end of HSlider constructor, it would do something like:

```js
options.componentCreated && options.componentCreated('track',track)
options.componentCreated && options.componentCreated('knob',knob)
```

Then the sim code that creates the HSlider can listen for these callbacks and register the components with together.  This will keep logic out of sun as much as possible while still allowing us to handle nested structures while maintaining encapsulation.  We will need to ensure that the componentCreated callbacks get passed through to children components and that they (a) don't use the same variable names or (b) pass through context or push/pop context.

**Comment by samreid** [comment]
A superior variant of the above comment appears in #85.

**Comment by jonathanolson** [comment]
This is assigned to me, but I presume tandem is a preferred approach?

**Comment by samreid** [comment]
Yes, @jonathanolson #85 is the preferred approach now.  Can you review it when you have time and make sure it seems ok?
