### ISSUE TITLE
Chart example not charting?

### ISSUE THREAD

**Issue by hirokiterashima** [phetsims/together#9]
Mac OSX 10.10.1
FF35
Chrome 40.0.2214.94

I launched the demo on the chart example (#7):
https://github.com/phetsims/together/blob/gh-pages/README.md#example-chart

No matter what I do, nothing seems to get charted on the right of the simulation.

![screen shot 2015-01-31 at 1 10 12 pm](https://cloud.githubusercontent.com/assets/119416/5989853/98bd1cae-a94a-11e4-8c20-945c8b459b22.png)

**Comment by samreid** [comment]
Thanks for this issue report. The problem is that the data is sampled from the frontmost barometer, but only when it is dragged out of its toolbox.  I'll revise the documentation to make this more clear.

**Comment by samreid** [comment]
I revised the documentation, you can see the diff above or the full context at: https://github.com/phetsims/together/blob/gh-pages/README.md#example-chart

@hirokiterashima can you please review it and see if this solves the problem?  Again, thank you for the report and let me know if you see any other issues.

**Comment by hirokiterashima** [comment]
Got it. Thanks for the clarification.
