### ISSUE TITLE
what does 'ForReleasedDisabled' mean?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/together#90]
In MomentaryButtonModel:

```js
   var enabledListener = function() {
      self.trigger0( 'startedCallbacksForReleasedDisabled' );
      onProperty.set( false );
      self.trigger0( 'endedCallbacksForReleasedDisabled' );
    };
```

I understand the 'startedCallbacks' and 'endedCallbacks' prefix.  But what the heck is 'ForReleasedDisabled'?

**Comment by pixelzoom** [comment]
Perhaps it means that the callbacks are related to the button transitioning to the released state as the result of having been disabled (as distinct from the user releasing the button)?  How about startedCallbacksForReleasedByDisable?

**Comment by samreid** [comment]
That is precisely what it means, I implemented your recommendation above.  Closing.
