### ISSUE TITLE
Namespace all tandems based on the sim name

### ISSUE THREAD

**Issue by samreid** [phetsims/together#92]
Currently tandems are assigned based on a screen-by-screen basis, but in order to gracefully scale up to multi-sim studies, it would be more convenient to prefix labels with the name of the sim as well.

On the other hand, this would increase the verbosity of query parameters, data transmission, etc.  May make zip compression much more important.

We should discuss it, but at the moment I'm leaning toward namespacing everything based on the sim.  There is another issue too that dealt with this but I haven't searched for it yet.

**Comment by samreid** [comment]
Could be good to do this sooner rather than later so that various groups will get the long-term messages (if we agree this is a good plan).

**Comment by pixelzoom** [comment]
+1 for namespacing tandems with the repository name (if that's what you mean by "sim name").

**Comment by samreid** [comment]
Well, I think we would camel-case it like "energySkateParkSim" instead of hyphens like the repo name "energy-skate-park-sim".  Sound OK?

Also, do you like putting "sim" here or "simulation"?

**Comment by pixelzoom** [comment]
Camel case sounds good. Is add the "sim" or "simulation" suffix really necessary?

**Comment by samreid** [comment]
Just thinking through some possible names with and without:

```
beersLawLab.concentrationScreen.resetAllButton
beersLawLabSim.concentrationScreen.resetAllButton
beersLawLabSimulation.concentrationScreen.resetAllButton
```

The first one seems good to me.  I guess by convention we would know it is a sim?

**Comment by pixelzoom** [comment]
As long as you don't mind this one:

```
beaker.beakerScreen.resetAllButton
```

This will be the case with all single-screen sims, the first first two tokens will be X.XScreen, where X is the repo name.

**Comment by samreid** [comment]
@jbphet & I have moved toward this and completed it for several sims.  All future instrumented sims should follow this pattern.  Closing.
